package com.zhenhua.microread.mapper;

import com.zhenhua.microread.entity.Commet;

public interface CommetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commet
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commet
     *
     * @mbg.generated
     */
    int insert(Commet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commet
     *
     * @mbg.generated
     */
    int insertSelective(Commet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commet
     *
     * @mbg.generated
     */
    Commet selectByPrimaryKey(String commentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commet
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Commet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table commet
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Commet record);
}