package com.zhenhua.microread.mapper;

import com.zhenhua.microread.entity.ShareCategory;

public interface ShareCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     */
    int insert(ShareCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     */
    int insertSelective(ShareCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     */
    ShareCategory selectByPrimaryKey(String categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ShareCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table share_category
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ShareCategory record);
}